# Python Basic

책 **파이썬으로 배우는 머신러닝의 교과서** 내용을 넣은 내용입니다.

## 사칙 연산

### 사칙 연산의 이용

In [ ]:
1+2

3

### 제곱
제곱은 **로 나타낸다.

In [ ]:
2 ** 8

256

## 변수

### 변수를 이용한 계산

In [ ]:
x = 1
y = 1 / 3
x + y

1.3333333333333333

### 변수명의 표기
여러 문자열로 표기 가능

In [ ]:
Data_1 = 1 / 5
Data_2 = 3 / 5
Data_1 + Data_2

0.8

## 자료형

### 자료형의 종류

자료형 종류
- int 형 : 정수 | a = 1
- float 형 : 실수 | a = 1.5
- str 형 : 문자열 | a = "learning"
- bool 형 : 참과 거짓 | True or False
- list 형 : 배열 | a = `[1,2,3]`
- tuple 형 : 배열(수정 X) | a = (1,2,3)
- ndarray 형 : 행렬 | a = np.array([1,2,3])


In [ ]:
print(type(100))
print(type(100.1))

<class 'int'>
<class 'float'>


### 문자열

In [ ]:
x = 'learning'
type(x)

str

## print문

### 이용
print문 안쓰면 주피터 노트북 기준 맨 마지막 셀만 출력함

In [ ]:
x = 1 / 3
x
y = 2 / 3
y

0.6666666666666666

이 때 print 씀

In [ ]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


### 문자열과 수치를 함께 표시1

str 형에서 +란 두 str형을 합치는 개념임

In [ ]:
print('x= ' + str(x))

x= 0.3333333333333333


### 문자열과 수치를 함께 표시2

`format`쓰면 좀 편함

In [ ]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


{0} 부분을 x의 내용으로 대체한다는 뜻임. 근데 이것보다 최근에 나온 **f-string**이 훨 편함

## list

### list의 이용
여러 데이터를 하나의 단위로 취급하고 싶은 경우, 즉 배열 변수를 사용하고 싶은 경우에 list형을 사용함.

In [ ]:
x = [1, 1, 2 ,3, 5]
x

[1, 1, 2, 3, 5]

In [ ]:
x[1]

1

In [ ]:
x[2]

2

In [ ]:
print(type(x))
print(type(x[1]))

<class 'list'>
<class 'int'>


In [ ]:
s = ['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


### 2차원 배열

In [ ]:
a=[[1,2,3], [4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
a=[[1,2,3], [4,5,6]]
print(a[0][1])

2


### list의 길이

In [ ]:
x = [1, 1, 2, 3, 5]
len(x)

5

### 연속된 정수 데이터의 작성

5에서 9까지의 같이 연속된 정수 데이터를 만드려면 `range(시작숫자, 끝숫자 + 1)`사용함

In [2]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


근데 겉보기에는 List형 같지만, 메모리를 절약한 데이터 형식인 `range형`이 됨.

In [4]:
print(y)

range(5, 10)


range형은 list형처럼 참조는 가능할지언정 요소 수정은 불가능함. 다만 range형은 `list` 함수를 사용하여 요소를 수정할 수 있는 list 형으로 변환할 수 있음.

In [6]:
z = list(range(5, 10))
print(z)

[5, 6, 7, 8, 9]


시작숫자를 생략하고 `range(끝숫자+1)`을 입력하면 **0부터 시작되는 수열**이 만들어짐

In [8]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## tuple 

### tuple의 이용

tuple은 list와 달리 요소를 수정할 수 없음. tuple 형은 **()** 를 이용하여 배열을 나타냄

In [9]:
a = (1,2,3)
print(a)

(1, 2, 3)


요소의 참조는 list와 동일함. 그리고 tuple은 함수의 출력이 여러 개인 경우에 자동으로 정리됨. 혹은 기존 함수의 입력이 tuple 형으로 지정될 수 있음.

In [11]:
type(a)

tuple

### 길이가 1인 tuple

(1)인 튜플도 있을까? 괄호 안에 하나만 넣을 경우 ()의 의미는 tuple이 아닌 **연산의 순서 기호**로 표시됨!
길이가 1인 tuple은 **(1,)**과 같이 쉼표를 붙임 

In [12]:
a = (1)
type(a)

int

In [13]:
a = (1,)
type(a)

tuple

## if문

흔한 조건문 중 하나

파이썬은 이런 들여쓰기로 조건문, 반복문 등의 실행 코드를 구분하기 때문에 상당히 중요함!

In [14]:
x = 11
if x > 10:
  print('x is ')
  print('      larger than 10.')
else:
  print('x is smaller than 11')

x is 
      larger than 10.


In [16]:
x > 10

True

In [17]:
type(x > 10)  # bool 형

bool

### 비교 연산자
'>'를 비교 연산자라고 부름. 비교 연산자 종류는 타 언어와 차이 X
연산의 결과는 모두 bool 형

여러 조건을 사용할 시 **and**, **or**을 사용함.

In [18]:
x = 15
if 10 <= x and x <= 20:
  print('x is between 10 and 20.')

x is between 10 and 20.


## for문

흔한 반복문1

### 사용 방법

for문이라고 신나서 C언어 처럼 사용하면 안됨. for문은 `for "변수" in "list 형"`과 같은 형태임. list형 대신 tuple형, range형 ㅆㄱㄴ

In [19]:
for i in [1, 2, 3]:
  print(i)

1
2
3


In [21]:
num = [2, 4, 6, 8 ,10]
for i in range(len(num)):
  num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


### enumerate

생소할 수 있는 기능 중 하나, 위에서 구현한 기능을 좀 더 우아하게 즐기기 ㄱㄴ 두 개의 변수를 사용해서 전자는 배열 크기에 맞는 인덱스, 후자는 해당 인덱스의 배열 값을 집어 넣어줌

In [22]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
  num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


## 벡터

암 벡터맨~

파이썬으로 바로 벡터 처리 가능할까? ( [1, 2] + [3, 4] = [4, 6]) 결과적으론 안됨... list형을 서로 더하면 str형과 동일하게 '+ 연산자'로 해석되어 연결하기 때문.

In [23]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

### numpy의 이용

안타깝게도 python 기본 내장 라이브러리는 벡터를 구현할 길이 없음. 어거지로  가능은 할 지 언정 좀 더 편한 라이브러리를 사용. import로 라이브러리를 훔쳐와서 사용함. as는 긴 라이브러리 이름을 내 맘대로 해주어 라이브러리 호출 편하게 ㄱㄴ

In [2]:
import numpy as np

### 벡터의 정의

벡터(1차원 배열)은 `np.array(list 형)`으로 정의함
`print()` 할 시 list, tuple과는 달리 ,가 생략되어 있음!

In [25]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
print(x)

벡터간 덧셈 ㅆㄱㄴ

In [27]:
y = np.array([4, 5, 6])
print(x + y)

[5 7 9]


In [28]:
type(x)

numpy.ndarray

### 요소 참조 & 수정

list형과 똑같음

In [29]:
x[0]

1

In [30]:
x[0] = 100
print(x)

[100   2   3]


### 연속된 정수 벡터의 생성

`np.arange(n)`으로 요소의 값이 1씩 증가하는 벡터 배열 만들기 ㅆㄱㄴ

In [31]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


`arange(n1, n2)`를 사용하면 **n1**부터 **n2-1**까지의 배열이 만들어짐.

In [33]:
print(np.arange(5, 10))

[5 6 7 8 9]


### 주의점

예를 다른 변수에 심을려면 그냥 들고와서는 안됨. ndarray 자료형에 내장되어 있는 기능 중 `copy`를 사용해야 함. 단순히 b = a와 같이 대입하면 a의 내용이 저장된 곳의 참조 주소가 전달됨.(포인터 개념, 즉 ndarray는 주소값들이 뭉쳐져있고 값을 가져오는 건 포인터 참조라고 생각하면 편할 듯) 즉, a와 b가 연결되어 둘 중 하나라도 변경시 같이 변경됨.

In [37]:
a = np.array([1, 1])
b = a  # 주소 복사
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1 1]
b = [1 1]
a = [100   1]
b = [100   1]


In [39]:
a = np.array([1, 1])
b = a.copy()  # 독립 메모리 공간 할당
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1 1]
b = [1 1]
a = [1 1]
b = [100   1]


## 행렬

이산수학의 꽃

### 정의

2차원 배열로 정의 ㅆㄱㄴ

In [40]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


### 크기
행렬(배열)의 크기는 **ndarray변수명.shape** 명령으로 알 수 있음

In [42]:
x = np.array([[1, 2, 3],[4, 5, 6]])
x.shape # 2행 3열

(2, 3)

이 출력은 tuple형으로 나타나는데, 얘네 각각을 변수에 집어넣을 수 있음. 각 행과 열의 크기는 데이터 분석에 큰 도움이 되니 넣는 방법을 익히면 편할듯

In [43]:
w, h = x.shape
print(w)
print(h)

2
3


### 요소의 참조

요소를 참조하려면 다음과 같이 차원마다 ','로 구분하여 나타냄. 마치 C언어의 2차원 배열과 같음

일케치면 C언어로 numpy 구현도 ㄱㄴ할듯

In [4]:
x = np.array([[1,2,3],[4,5,6]])
x[1, 2]

6

### 요소의 수정
list형과 비슷하게 수정 ㄱㄴ

In [6]:
x = np.array([[1,2,3],[4,5,6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


### 요소가 0 or 1인 ndarray

모든 요소가 0인 ndarray는 `np.zeros(size)`로 ㄱㄴ 매개변수 2개 넣으면 해당 크기만큼의 행렬을 생성함. 1은 `np.ones(size)`로 完

In [10]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
print(np.zeros((2, 10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
print(np.ones((2, 10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 요소가 랜덤인 행렬 생성

`np.random.rand(size)`를 사용. 각 요소는 0에서 1 사이의 균일한 분포를 보이며 행렬 형태로 생성. 이 때 사이즈는 tuple이 아님!

In [13]:
np.random.rand(2, 3)

array([[0.01587489, 0.97419347, 0.7398057 ],
       [0.5024898 , 0.63998282, 0.73861679]])

`np.random.randn(size)`을 사용하면 평균 0 분산 1의 가우스 분포 난수 생성 ㄱㄴㄴ

In [14]:
np.random.randn(2, 3)

array([[-1.02631098, -0.65566271,  1.32138798],
       [ 1.37406162, -0.01459117, -1.42611578]])

`np.random.randint(low, high, size)`를 사용하면 `low`에서 `high`까지의 임의의 정숫값으로 이뤄진 `size` 크기의 행렬 생성 ㄱㄴ

In [16]:
np.random.randint(1, 5, 2)

array([4, 2])

### 행렬 크기 변경

`변수명.reshape(n, m)`을 사용

In [17]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 행렬의 사칙연산

이산수학에서... 다들 뼈빠지게 계산해봤죠? ㅠㅠ

### 사칙 연산

모든 사칙 연산 ㄱㄴ

In [19]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


### 스칼라 x 행렬

In [20]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


### 산술 함수

- `np.exp(x)` : 지수 함수
- `np.sqrt(x)`: 제곱근
- `np.log(x)` : 로그
- `np.round(x, 유효자릿수)` : 반올림
- `np.mean(x)`: 평균
- `np.std(x)` : 표준 편차
- `np.max(x)` : 최댓값
- `np.min(x)` : 최솟값


In [21]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


### 행렬 곱의 계산

요소별로 계산하지 않는 행렬 곱은? `변수명1.dot(변수명2)`로 계산 ㄱㄴ

In [23]:
v = np.array([[1, 2, 3], [4, 5 ,6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v.dot(w))

[[14 14]
 [32 32]]


## 슬라이싱

어맛 미끄러졌네

### 이용
요소를 한번에 나타낼 수 있는 점이 큰 매력임

In [26]:
x = np.arange(10)
print(x)
print(x[:5])  # :5는 첫 번째부터 5번째까지
print(x[5:])  # 위와 반대

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]


In [27]:
print(x[3:8])  # 어디서부터 어디까지??

[3 4 5 6 7]


In [28]:
print(x[3:8:2]) # 세번째 값 간격으로 참조됨

[3 5 7]


In [30]:
print(x[::-1])  # reverse!

[9 8 7 6 5 4 3 2 1 0]


In [31]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


## 조건을 만족하는 데이터의 수정

### bool 배열 사용

넘파이를 통하여 행렬 데이터에서 특정 조건을 만족하는 것을 추출하여 쉽게 수정 ㄱㄴ

In [32]:
x = np.array([1,1,2,3,5,8,13])
x > 3

array([False, False, False, False,  True,  True,  True])

true인 값만 뽑아낼 수도 있음

In [34]:
x[x > 3]

array([ 5,  8, 13])

조건이 충족/불충족되는 값만 바꾸라고 할 수 있음!

In [35]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


## Help

도..도와줘! 아니 도움말만 뱉지 말고!!

### Help 사용

함수의 설명을 확인해줌. 그냥 이런게 있다고 받아들이삼~~



In [37]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

## 함수

ㅇㅇ 너가 아는 그 함수 맞음

`def()`로 만듦

In [38]:
def my_func1():
  print('Hi!')

my_func1()

Hi!


인수랑 반환값 다 줄 수 있다는거 알제?

In [39]:
def my_func3(D):
  m = np.mean(D)
  s = np.std(D)
  return m, s

In [40]:
data = np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean: {0:3.2f}, std: {1:3.2f}'.format(data_mean, data_std))

mean: -0.08, std: 0.86


반환값이 여러 개여도 하나의 변수 받는거 ㅆㄱㄴ. 글고 받게 되면 그 자료형은 tuple로 받아야함

In [41]:
output = my_func3(data)
print(output)
print(type(output))
print('mean: {0:3.2f}, std: {1:3.2f}'.format(output[0], output[1]))

(-0.08269818798192215, 0.8555875103281246)
<class 'tuple'>
mean: -0.08, std: 0.86


## 파일 저장

사라지면... 가슴 아프지나...

### 하나의 ndarray 형을 저장

`np.save('파일명.npy', 변수명)`을 사용. 파일의 확장자는 **.npy**임. 데이터를 로드하려면 `np.load('파일명.npy')`을 사용

In [43]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy', data)    # 저장
data = []                        # 데이터 삭제
print(data)
data = np.load('datafile.npy')
print(data)

[ 0.83356066  0.93685196  0.22925403 -0.02270531 -1.07711426]
[]
[ 0.83356066  0.93685196  0.22925403 -0.02270531 -1.07711426]


### 여러 ndarray형을 저장

여러 ndarray형을 한번에 저장! `np.savez('파일명.npz', 변수명1 = 변수명1, 변수명2 = 변수명2, ...)`

In [45]:
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1=data1, data2=data2)
data1 = []                        # 데이터 삭제
data2 = []   
outfile = np.load('datafile2.npz')
print(outfile.files)

data1 = outfile['data1']
data2 = outfile['data2']
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
